# Change these first
owner: yanyao2333 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://www.roitium.com
  - name: Self-hosted Bitwarden
    url: https://passwd.roitium.com
  - name: Self-hosted FreshRSS
    url: https://rss.roitium.com
  - name: Self-hosted Memos
    url: https://memos.roitium.com
    expectedStatusCodes:
      - 200
      - 201
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: 
  name: Upptime
  introTitle: "Welcome to my monitor panel!"
  introMessage: Is everything ok?
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
